version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: teamtrack-postgres
    environment:
      POSTGRES_DB: teamtrack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: teamtrack-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

  webapi:
    build: .                          # Tells Docker to look for a 'Dockerfile' in this same folder
    container_name: teamtrack-api
    ports:
      - "8080:8080"                   # Changes depending on what port the app listens to
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=teamtrack;Username=postgres;Password=postgres
    depends_on:
      - postgres                      # Makes sure the database starts before your app tries to connect

volumes:
  postgres_data:
